### ISSUE TITLE
Linux binaries?

### ISSUE THREAD

**Issue by Sush-ruta** [spel987/PolyUploader#2]
This seems like a really useful app that I'd love to try. If you could provide linux binaries (deb and/or appimages), that'd would be awesome.
All the best and thank you for developing this app. :)

**Comment by spel987** [comment]
Hello, I'm having trouble creating a .deb bundle, so I'm going to make a demonstration website available soon.
I've been working on a new version for a while and hope to release it soon! It should be pretty good...

**Comment by spel987** [comment]
Hello, I'm going to close this issue by giving you the demonstration link: https://p-u.vercel.app/demonstration.
I hope you'll enjoy it!
